import { mkdir, readFile, writeFile, cp, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const core = await readFile('public/core.js', 'utf8');
await mkdir('apps-script', { recursive: true });
await writeFile('apps-script/Code.gs', '// Generated by scripts/build.mjs. Do not edit this copy.\n' + core.replace(/^export /gm, '') + '\n' + await readFile('src/apps-script.js', 'utf8'));
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
// Every release gets a distinct offline shell, so future changes cannot use an old bundle.
const hash=createHash('sha256');
for(const file of (await readdir('public')).sort())hash.update(await readFile('public/'+file));
await writeFile('dist/sw.js',(await readFile('public/sw.js','utf8')).replace('__ASSET_VERSION__',hash.digest('hex').slice(0,16)));
console.log('Built static site and Apps Script bundle.');
