import { mkdir, readFile, writeFile, cp } from 'node:fs/promises';
const core = await readFile('public/core.js', 'utf8');
await mkdir('apps-script', { recursive: true });
await writeFile('apps-script/Code.gs', '// Generated by scripts/build.mjs. Do not edit this copy.\n' + core.replace(/^export /gm, '') + '\n' + await readFile('src/apps-script.js', 'utf8'));
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
console.log('Built static site and Apps Script bundle.');
